# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
  builder: html  # Default Sphinx builder to maintain compatibility

# Specify the location of the pre-built HTML files
extra:
  build_dir: docs/build  # Adjust this to the path where your built HTML files are stored

# Install your dependencies, if necessary
python:
  install:
    - requirements: docs/requirements.txt
