# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - pip install --upgrade pip
      - pip install -r docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py