# Read the Docs configuration file for Sphinx-based projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # Optional: Fetch full git history if needed for version calculation
      - git fetch --unshallow || true
    post_create_environment:
      # Install dependencies from requirements.txt
      - pip install -r docs/requirements.txt

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/conf.py

# Add nbsphinx explicitly if it’s not in your requirements file
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
    - method: pip
      packages:
        - nbsphinx
