# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

  # Disable the default Sphinx build process
  build-html: false

sphinx:
  builder: none  # Disable Sphinx builds

# Add this section to serve pre-built HTML files
documentation_type: "sphinx_html"

# The directory where your pre-built HTML files are stored
python:
  install:
    - method: pip
      path: .

# Ensure the correct directory is set for your HTML files
extra:
  build_dir: docs/build
