log_file: "error.log"
data_file_path: "./data/"
file_path_to_simulation: "Seq_Sim/seq_sim.py"
functions_script_path: "Seq_Sim/utils/seq_sim_utils.py"
file_prefix: "sim_data"

num_samples:
  - 10
  - 20
  - 30
fold_changes:
  - 0.1
  - 0.75
  - 1.5
  - 3

n_threads: 4

dummy_dataset_params:
  n_cells: 100 # cells per individual #PER CELLTYPE
  sd_celltypes: 0.1 # standard deviation of number of cells
  n_major_cell_types: 7
  n_minor_cell_types: 3
  relative_abundance: 0.4 # ratio between major and rare
  n_major_diff_celltypes: 1
  n_minor_diff_celltypes: 1
  n_batchs: 4
  prop_sex: 0.5 # proportion of feature 1 if feature 1 is categorical variable
  prop_disease: 0.5 # proportion of feature 2 if feature 2 is categorical variable
  seed: 1234
  n_features: 1000

variance_attributes: 
  cluster_ratio: 0.7

ratio_variance: 0.1

column_information:
  cluster_col: "cell_type"
  disease_col: "disease"
  individual_col: "subject_id"

files_to_save:
  feature_matrix: True
  latent_factors: True