name: Run Tests

on:
  push:
    branches:
      - main  # Run on pushes to main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml  # Point to your env.yml file
        auto-activate-base: false

    - name: Activate environment and run tests
      run: |
        conda activate base  # Activate the conda environment
        pytest test/seq_test.py  # Run your tests
