name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        shell: bash -el {0}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: som-sim-env

      # Print Conda environment info (for debugging)
      - name: Print Conda Environment Info
        run: conda info --envs

      # Install pytest and coverage if not in environment.yml
      - name: Install pytest and coverage
        run: |
          conda activate som-sim-env
          conda install pytest pytest-cov -y

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          conda activate som-sim-env
          export PYTHONPATH=$(pwd)
          coverage run -m pytest test/ -v
          pytest --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
