name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        shell: bash -el {0}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python version using Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-update-conda: true
          environment-file: env.yml
          activate-environment: som-sim-env

      # Print Conda environment info (for debugging)
      - name: Print Conda Environment Info
        run: conda info --envs

      # Run tests with pytest
      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$(pwd)
          pytest test/ -v